# Generated by Django 3.1.7 on 2021-03-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anorakapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwhiskey',
            old_name='list_image_url',
            new_name='list_img_url',
        ),
        migrations.RenameField(
            model_name='whiskey',
            old_name='list_image_url',
            new_name='list_img_url',
        ),
    ]
