# Generated by Django 3.1.7 on 2021-03-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anorakapi', '0003_remove_whiskey_comparable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiskey',
            name='tag',
        ),
    ]
