# Generated by Django 3.1.7 on 2021-03-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anorakapi', '0004_remove_whiskey_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwhiskey',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
