# Generated by Django 3.1.7 on 2021-03-20 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anorakapi', '0007_auto_20210320_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwhiskey',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
